org.gradle.daemon=true
org.gradle.jvmargs=-Xms512M -Xmx1G
org.gradle.configureondemand=false

# Versions
gdxVersion=1.12.1
junitVersion=5.10.0
mockitoVersion=5.5.0
projectVersion=1.0-SNAPSHOT

# GraalVM Native Image (optionnel - mettre à 'true' pour activer)
enableGraalNative=false
graalHelperVersion=1.12.1.1
